FROM nvidia/cuda:11.2.0-base-ubuntu20.04

# Location of source code
ENV PROJECT_ROOT /opt/project
RUN mkdir -p $PROJECT_ROOT
WORKDIR $PROJECT_ROOT

# Update, install Python 3.9 and curl
RUN apt-get update && \
    apt-get install -y python3.9 python3.9-distutils curl && \
    apt-get clean

# Install pip for Python 3.9
RUN curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py && \
    python3.9 get-pip.py && \
    rm get-pip.py

# Install libGL for OpenCV
RUN apt-get update && \
    apt-get install -y libgl1-mesa-glx libglib2.0-0 && \
    rm -rf /var/lib/apt/lists/*

# Copying dependencies
COPY ./requirements.txt .
RUN python3.9 -m pip install -r requirements.txt

COPY ./src ./src
COPY ./dataset ./dataset
COPY ./tmp ./tmp

RUN apt-get update -y && \
    apt-get install -y vim curl && \
    rm -rf /var/lib/apt/lists/*
