version: '3.8'
services:
  transformergpu:
    build:
      dockerfile: Dockerfile-gpu
    volumes:
      - "./src/:/opt/project/src"
      - "./dataset/:/opt/project/dataset"
      - "./tmp/:/opt/project/tmp"
    tty: true
