version: '3.8'
services:
  transformergpuv2:
    build:
      dockerfile: Dockerfile-gpu
    image: captioning-transformergpuv2
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all 
    volumes:
      - "./src/:/opt/project/src"
      - "./dataset/:/opt/project/dataset"
      - "./tmp/:/opt/project/tmp"
    tty: true
